#define DOUBLE                1
#define INTEGER               2 
#define FUNCTION              3
#define END                   4
#define IF                    5
#define FOR                   6
#define IDENTIFIER            7
#define COMMA                 8
#define DOT                   9
#define ENDLINE               10
#define OPENPARENTHESIS       11
#define CLOSEPARENTHESIS      12
#define OPENBRACKET           13
#define CLOSEBRACKET          14
#define OPENBRACE             15
#define CLOSEBRACE            16    
#define AND                   17
#define OR                    18
#define EQUAL                 19
#define DIFFERENT             20
#define ASSIGN                21
#define LESS                  22
#define LESSOREQUAL           23
#define GREATER               24
#define GREATEROREQUAL        25
#define PLUS                  26
#define MINUS                 27
#define MULTIPLY              28
#define DIVIDE                29
#define EXPONENTIAL           30
#define ELSE                  31
#define ELSEIF                32
#define SWITCH                33
#define CASE                  34
#define OTHERWISE             35
#define WHILE                 36
#define CONTINUE              37
#define BREAK                 38
#define RETURN                39
#define DOTDOT                40
#define DIVIDELINEAR          41